### PR TITLE
Add ModelBasedResource#get_schema

### PR DESCRIPTION
**Pull request by caseywebdev**
[As suggested here](https://github.com/closeio/closeio/pull/11862#issuecomment-412105548), this PR adds a `get_schema` method that allows the schema for a resource to be changed at runtime. This is nonbreaking because it defaults to the existing `self.Meta.schema`. I also noticed we had a `get_model` method, but we were referencing `self.Meta.model` in the methods instead of invoking  `get_model`, so I updated that as well.

### CODE REVIEW

**Review by thomasst — APPROVED** [review]
Looks good. The only thing I was debating is if it makes sense to call it `get_schema_class` / `get_model_class` for additional clarity, but I don't have a strong opinion either way.

**Comment by caseywebdev** [comment]
Backbone has this dilemma with the `Collection.model` attribute (`model` is a class). IMO `get_*_class` is more clear, but are we worried about breaking the API for `get_model`?

**Comment by thomasst** [comment]
> Backbone has this dilemma with the Collection.model attribute (model is a class). IMO get_*_class is more clear, but are we worried about breaking the API for get_model?

If you think it's more clear then I'm fine with breaking it.

I currently found these two places where we use it:
- https://github.com/closeio/dialer/blob/master/dialer/resources.py#L58
- https://github.com/closeio/closeio/blob/master/closeio/common/rest.py#L64

**Comment by caseywebdev** [comment]
Updated, I'll update those two instances of `get_model` in a closeio PR.

**Review by thomasst — APPROVED** [review]

**Pull request merged**
